//@execute =!BoundsCheckException
def f(x: range<int>) -> int {
	return x[0];
}

def main() -> int {
	def x: Array<int> = null;
	return f(x);
}
